### ISSUE TITLE
Issue with devDependencies and Angular internal dependencies

### ISSUE THREAD

**Issue by killianperea** [liferay/liferay-npm-build-tools#81] opened 2018-03-02 13:23 UTC
Hi,
I'm using liferay-npm-bundler in order to build portlets with Angular 4.4.4 and I'm getting errors with third-parties libraries like PrimeNG (https://www.primefaces.org/primeng/#/) because primeNG uses devDependencies instead of dependencies. this causes the bundler is not generating the right portlet. In addition, I'm getting errors with Angular internal dependencies, to be more specific on the Animation module.

Animations module need Browser module but the bundler is not able to "see" this and the portlet generated crash with the message "animation.js not found". Also I put the peerDependencie on the .npmbundlerrc but it didn't works.

Could I do something to make the bundler look up the devDependencies? 

Thanks for all, Killian.

**Comment by izaera** [comment] 2018-03-05 16:52
Hi there:

The animations error was fixed in this [issue](https://github.com/liferay/liferay-npm-build-tools/issues/66) which was released with v1.3.0 of the build tools. So just check the versions you are using and update them as necessary and it should work. If it doesn't just ask again :-).

Regarding the devDependencies, it doesn't make any sense to package them as they are supposed to be used for development, not during runtime, so the bundler doesn't do it. 

Do you know why PrimeNG is using devDependencies instead of plain dependencies?

Cheers,
Ivan

**Comment by killianperea** [comment] 2018-03-05 18:45
Hi!

I updated the version of the bundle to the 1.3.0 but I still got the same error:

![image](https://user-images.githubusercontent.com/12435335/36993101-32b01fd2-20ad-11e8-93d2-ead7277dadca.png)

My .npmbundlerrc looks like this:
![image](https://user-images.githubusercontent.com/12435335/36993154-561f28aa-20ad-11e8-9d8a-92e3af67516f.png)

I'm doing something wrong? 

Regarding the PrimeNG question, I dont know why they do it this way but I had had to fork the repo and put the devDependencies into the dependencies field.

Kr, Killian.

**Comment by izaera** [comment] 2018-03-06 08:01
> I updated the version of the bundle to the 1.3.0 but I still got the same error:

Can you paste your package.json?

Also, have you deleted `node_modules` and run `npm install` again? Otherwise you may still have the old bundler plugins hanging around...

**Comment by killianperea** [comment] 2018-03-06 08:35
Yes I did :) this is my package.json:
![image](https://user-images.githubusercontent.com/12435335/37021922-8f29896e-2121-11e8-8d7c-55cd03e1af72.png)

Do you see something wrong? should I do Blade gw clean before?

**Comment by killianperea** [comment] 2018-03-06 09:12
well, I'm trying to generate portlets with the styles of PrimeNG putting those styles inside the styles of Liferay. I don't know if I explain myself well :S It's like "decorate" the theme of Liferay with the PrimeNG styles.

**Comment by izaera** [comment] 2018-03-06 09:16
As long as you deploy that as portlets (inside JAR files) there should be no problem 👍 .

**Comment by killianperea** [comment] 2018-03-06 09:27
Could we have an other channel more dynamic in order to speak about the issues that I'm facing? I'm working in a big project for a company and I will use your bundler in order to build angular portlets and this kind of help is so useful for us since you are the "father" of it

Reggarding the build, now im getting a super warn log with all the code :S:
 
![image](https://user-images.githubusercontent.com/12435335/37024361-e6815f1e-2128-11e8-8cd2-d10ac50e28c3.png)

**Comment by izaera** [comment] 2018-03-06 09:55
Mmm, not really :-(. 

In fact this channel is supposed to be for already diagnosed bugs that can be directly fixable, not to give support. This is because I'm in the development team and I cannot dedicate so much time to support users (only some free spare time like now or allocated time when a bug is clear and must be fixed).

Said that, if you or your company have a support contract, just file a LESA ticket and a support engineer will assist you directly with these issues. It will much more efficient :-).

**Comment by killianperea** [comment] 2018-03-06 10:02
Ok thanks for your response! :) I'm a little bit stuck on this, do you know what is happening in my comment above? :S

**Comment by izaera** [comment] 2018-03-06 10:07
To be honest I don't have any idea :-(. 

That's why I was suggesting to contact support because we have never seen such error with Angular and it may be caused by some other thing outside the npm support. It would need a good diagnostic...

Sorry.

You can also upload a ZIP file to be able to reproduce it locally, but I cannot guarantee when I will have time to look at it. It may be delayed quite a few days.

**Comment by killianperea** [comment] 2018-03-06 10:38
Ok, here you have the zip, If you can take a look of the code would be super nice! Take your time :)

[inputs-theme-liferay.zip](https://github.com/liferay/liferay-npm-build-tools/files/1784579/inputs-theme-liferay.zip)

thanks a lot for this help :D

**Comment by killianperea** [comment] 2018-03-06 12:00
Looking the README I notice this schema:
![image](https://user-images.githubusercontent.com/12435335/37031150-fc2189ba-213d-11e8-96d6-68345373e08e.png)

the node_modules is in the same level that the app but this is my project tree:

![image](https://user-images.githubusercontent.com/12435335/37031191-213930ae-213e-11e8-9bd4-4767cedc1c84.png)

Could this be the error? Since now The bundler found the node_modules right but maybe It's on a wrong place :/

**Comment by yuchi** [comment] 2018-03-06 12:18
The file structure in the README represents the final state *after* the bundling occurred.

**Comment by izaera** [comment] 2018-03-08 14:41
@killianperea I have reproduced your failure and it is fixable (except for the devDependencies). Just change your `.npmbundlerrc` file by this:

```
{
	"exclude": {
        "mkdirp": ["bin/**/*"],
		"chart.js": ["gulpfile.js"]
    },
	"*": {
		"plugins": [
			"replace-browser-modules",
			"inject-angular-dependencies"
		],
		".babelrc": {
			"presets": ["liferay-standard"]
		}
	}
}
```

It fixes some misconfigurations you had and excludes `gulpfile.js` of `chart.js` that was causing the bundler to fail.

**Comment by killianperea** [comment] 2018-03-08 16:07
@izaera thanks for your response, now I dont get that error but the error 
![image](https://user-images.githubusercontent.com/12435335/37161366-c0694118-22f2-11e8-9af9-49ae1304f440.png)

still happening, should I put the dependenciesMap?

**Comment by izaera** [comment] 2018-03-14 15:07
Hi again. 

I have released v1.5.0 of the build tools and checked that it works with the provided portlet and the current portal's master version.

In addition, I have added support to force inclusion of `devDependencies` as needed (see https://github.com/liferay/liferay-npm-build-tools/issues/82).

I will attach a new ZIP with the working version in case it can help you @killianperea .

Also, I will close this question as its main subject has been resolved. If you have any further doubts just create a new issue. Thx.

**Comment by izaera** [comment] 2018-03-14 15:12
[inputs-theme-liferay.tar.gz](https://github.com/liferay/liferay-npm-build-tools/files/1811724/inputs-theme-liferay.tar.gz)

**Closed by izaera** 2018-03-14 15:12 UTC
Labels: question

**Comment by killianperea** [comment] 2018-03-15 08:07
Hi, 
Sorry to speak on a closed thread (I dont know if It's a bad practice) but Its not about an issue of the bundle I think. I put your portlet on my Liferay and Still getting the animations error so I think could be the version of the Liferay. 

At this moment I'm using the "Liferay Community Edition Portal 7.0.4 GA5 (Wilberforce / Build 7004 / October 23, 2017)" with the Blade CLI version 2.3.1.201711201552. Can you see somethig wrong ? Can you say me the versions of Liferay and BladeCLI where you made the portlet works??

Kr, Killian
